name: flutter_auto_localizations
description: "A CLI tool to auto-translate Flutter ARB localization files using Google Translate."
version: 0.0.1
repository: https://github.com/DewminaUdayashan/flutter_auto_localizations
executables:
  flutter_auto_localizations: flutter_auto_localizations

environment:
  sdk: ^3.6.1

dependencies:
  dotenv: ^4.2.0
  http: ^1.3.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
